# Generated by Django 5.2.4 on 2025-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parks', models.IntegerField(default=0)),
                ('schools', models.IntegerField(default=0)),
                ('safety_score', models.FloatField(default=0.0)),
                ('transit_score', models.FloatField(default=0.0)),
                ('nightlife_score', models.FloatField(default=0.0)),
                ('income', models.IntegerField(default=0)),
            ],
        ),
    ]
