# Generated by Django 5.1.6 on 2025-07-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='nightlife_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='parks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='safety_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='schools',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='transit_score',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='matcher.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='matcher.city'),
        ),
    ]
