# Generated by Django 5.1.6 on 2025-07-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_area_city_neighborhood_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='matcher.area'),
        ),
    ]
